SET SCHEMA MY_SCHEMA;
INSERT INTO MY_TABLE (ONE, TWO, THREE) VALUES (1, "TWO", "THREE");
commit;
INSERT INTO MY_TABLE (ONE, TWO, THREE) VALUES (2, "TWO", "THREE");
commit;
INSERT INTO MY_TABLE (ONE, TWO, THREE) 
VALUES (3, "TWO", "THREE");
INSERT INTO MY_TABLE 
(ONE, TWO, THREE) VALUES (4, "TWO", "THREE");
INSERT INTO MY_TABLE (ONE, TWO, THREE) VALUES (5, "TWO", "THREE");
commit;
INSERT INTO MY_TABLE (ONE, TWO, THREE) VALUES (6, "TWO", "THREE");

INSERT INTO MY_TABLE (ONE, TWO, THREE) VALUES (7, "TWO", "THREE");




INSERT INTO MY_TABLE (ONE, TWO, THREE) VALUES (8, "TWO", "THREE");
commit;
INSERT INTO MY_TABLE (ONE, TWO, THREE) VALUES (9, "TWO", "THREE");
INSERT INTO MY_TABLE (ONE, TWO, THREE) VALUES (10, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (1, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (2, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (3, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (4, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (5, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (6, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (7, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (8, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (9, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (10, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (11, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (12, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (13, "TWO", "THREE");
INSERT INTO MY_OTHER_TABLE (ONE, TWO, THREE) VALUES (14, "TWO", "THREE");
